### ISSUE TITLE
get events

### ISSUE THREAD

**Issue by phenom1711** [sargue/mailgun#16]
hello, 
how i can get events like from this document 
https://documentation.mailgun.com/api-events.html

so i just need to add some parameter like this

curl -s --user 'api:key-b9b56136405e12192789fa414a5359bb' -G \
      https://api.mailgun.net/v3/bankjateng.co.id/events \
      --data-urlencode begin='Mon, 5 June 2017 00:00:00 -0000' \
      --data-urlencode ascending=yes \
      --data-urlencode pretty=yes \
      --data-urlencode event='rejected OR failed'
so if i need event that rejected OR failed with begin parameter i can catch them easy

**Comment by sargue** [comment]
Hi!

The library is designed only to send messages. All of the rest of features of the Mailgun service are not available through the library nor are any plans to support them at the moment.

You can use the Jersey client library to access the rest of the functionality.

Note, if the api key that you have pasted in the issue is real **you should change it immediately**. That is a secret key that you should not post on any public page like this.

**Comment by phenom1711** [comment]
thank you very much...
